#################################################
# DO NOT CHANGE 
CONFIG_NAME: 'text-to-image'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: 'data/birds'

IMAGE_SIZE: 256
CUDA: True

R_PRECISION_DIR: './evaluation'
R_PRECISION_FILE: 'r_precision.npz'
R_PRECISION_FILE_HIDDEN: 'r_precision_hidden.npz'
WRONG_CAPTION: 9

CHECKPOINT_DIR: './checkpoint'
#################################################

GPU_ID: '0'
WORKERS: 4
PRE_WORKERS: 1
LOAD_PRE_TRAIN: False

TREE:
    BRANCH_NUM: 3

PRE_TREE:
    BRANCH_NUM: 1
    BASE_SIZE: 299

PRE_TRAIN:
    FLAG: True
    NET_E: '' 
    BATCH_SIZE: 32
    MAX_EPOCH: 5 #600
    SNAPSHOT_INTERVAL: 50
    ENCODER_LR: 0.0005
    RNN_GRAD_CLIP: 0.25
    SMOOTH:
        GAMMA1: 4.0 
        GAMMA2: 5.0
        GAMMA3: 10.0

#################################################
# DO NOT CHANGE 
TRAIN:
    FLAG: True
#################################################
    NET_G: ''
    B_NET_D: True
    BATCH_SIZE: 12  # 22
    MAX_EPOCH: 5  #600
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    #
    NET_E: 'text_encoder.pth'
    SMOOTH:
        GAMMA1: 4.0 
        GAMMA2: 5.0
        GAMMA3: 10.0
        LAMBDA: 5.0

#################################################
# DO NOT CHANGE 
TEST:
    B_EXAMPLE: False
    GENERATED_TEST_IMAGES: './evaluation/generated_images'
    GENERATED_HIDDEN_TEST_IMAGES: './evaluation/generated_images_hidden'
#################################################
    BATCH_SIZE: 12  # 22

RNN:
    TYPE: 'LSTM'

GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    CONDITION_DIM: 100
    R_NUM: 2

#################################################
# DO NET CHANGE 
TEXT:
    CAPTIONS_PER_IMAGE: 10
#################################################
    EMBEDDING_DIM: 256
    WORDS_NUM: 18